const data = {
  products: [
    {
      name: "La Greca Shirt",
      slug: "la-greca-shirt",
      category: "shirt",
      image: "/images/image1.jpg",
      price: 1025,
      brand: "Versace",
      countInStock: 20,
      description:
        "Crafted in a lightweight cotton, this short-sleeved button-down shirt features the La Greca print and a relaxed camp collar.",
      details: [
        "La Greca print",
        "Short sleeves",
        "Camp collar",
        "Front button closure",
        "Side slits",
        "Outer Fabric: 52% Cotton, 48% Lyocell",
        "Outer Fabric 2: 52% Cotton, 48% Lyocell",
        "Machine wash cold (delicate)",
        "Do not bleach",
        "Do not tumble dry",
        "Cool iron on reverse with damp cloth on top",
        "Delicate dry clean",
        "Wash inside out",
      ],
      sku: "1003926-1A04992_5G320",
    },
    {
      name: "Barocco Silk Shirt",
      slug: "barocco-silk-shirt",
      category: "shirt",
      image: "/images/image2.webp",
      price: 1550,
      brand: "Versace",
      countInStock: 20,
      description:
        "Crafted from pure silk this short-sleeved button-down shirt features the signature Barocco print - a beloved house code featuring stylised acanthus leaves.",
      details: [
        "Barocco print",
        "Button down front",
        "Collar",
        "Outer fabric: 100% Silk",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1003926-1A03044_5B000",
    },
    {
      name: "Barocco T-Shirt",
      slug: "barocco-t-shirt",
      category: "shirt",
      image: "/images/image3.webp",
      price: 925,
      brand: "Versace",
      countInStock: 20,
      description:
        "In a slim silhouette, this short-sleeved cotton T-shirt features Versace's signature Barocco print - a beloved house code featuring stylised acanthus leaves.",
      details: [
        "Barocco print",
        "Short sleeves",
        "Ribbed crewneck",
        "Outer fabric: 100%  Cotton",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1006662-1A04612_5B000",
    },
    {
      name: "Barocco Shorts",
      slug: "barocco-shorts",
      category: "pants",
      image: "/images/image4.webp",
      price: 1225,
      brand: "Versace",
      countInStock: 20,
      description:
        "A comfortable design, these knee-length shorts are crafted from pure silk twill in the signature Barocco print.",
      details: [
        "Barocco print",
        "Lining: 100% Cupro",
        "Outer fabric: 100%  Silk",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1002476-1A03044_5B000",
    },
    {
      name: "Barocco Bucket Hat",
      slug: "barocco-bucket-hat",
      category: "headwear",
      image: "/images/image5.webp",
      price: 625,
      brand: "Versace",
      countInStock: 20,
      description:
        "A contemporary accessory, this bucket hat features the iconic Barocco print.",
      details: [
        "Barocco print",
        "Lining: 100% Polyamide",
        "Outer fabric: 100% Polyamide",
        "Do not bleach",
        "Do not dry clean",
        "Do not iron",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1001591-1A02963_5B000",
    },
    {
      name: "Metropolitano Check Wool Pants",
      slug: "metropolitano-check-wool-pants",
      tags: ["Runway Show"],
      category: "pants",
      image: "/images/image6.webp",
      price: 1950,
      brand: "Versace",
      countInStock: 20,
      description:
        "A painterly Metropolitano Check motif outlines these tapered formal pants. A tailored style, they are finished with a front pleat and a concealed hook and zip closure.",
      details: [
        "Metropolitano Check print",
        "Belt loops",
        "Tapered fit",
        "Side pockets",
        "Concealed hook and zip closure",
        "Back welt pockets",
        "Outer Fabric: 100% Pure Virgin Wool",
        "Lining 1: 100% Cupro",
        "Lining 2: 100% Cotton",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
        "Cool iron",
        "Delicate dry clean",
      ],
      sku: "1006714-1A04925_5E050",
    },
  ],
};

export default data;
