import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@testing.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@testing.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  catalogue: {
    men: {
      title: "Men's Collection",
      subtitle:
        "Get the quintessential Versace look by pairing the latest runway styles with a statement bag and modern shoes. For the finishing touch, browse an array of luxurious accessories.",
      clothing: {
        name: "Clothing",
        title: "Men's Clothing",
        subtitle:
          "A fashionable selection of menswear - an array of suits, shirts, T-shirts, coats, jackets, pants and jeans for men with impeccable style.",
        "pants-shorts": {
          name: "Pants & Shorts",
          slug: "pants-shorts",
          title: "Men's Pants and Shorts",
          subtitle:
            "Versace pants and shorts for men in an array of styles and fits, from tailored formal pants to comfortable sweatpants and print silk shorts.",
        },
        shirts: {
          name: "Shirts",
          slug: "shirts",
          title: "Men's Shirts",
          subtitle:
            "Crafted from smooth silk or cotton, Versace shirts for men bring elegance and personality. Various designs are enhanced by bold prints and heritage embellishments. Crisp formal button shirts complete a business formal or casual look when paired with a blazer or tie.",
        },
        sweatshirts: {
          name: "Sweatshirts",
          slug: "sweatshirts",
          title: "Men's Sweatshirts and Hoodies",
          subtitle:
            "A casual yet Very Versace look—the Versace collection of luxury sweatshirts and hoodies for men featuring logo sweatshirts and signature printed hoodies.",
        },
        "t-shirts-polos": {
          name: "T-Shirts",
          slug: "t-shirts-polos",
          title: "Men's T-Shirts & Polos",
          subtitle:
            "Browse a selection of t-shirts and polo shirts for men, crafted from comfortable and fine fabrics and embellished with signature prints. Slip on a t-shirt with a pair of Versace jeans and shoes .",
        },
        "jackets-coats": {
          name: "Jackets & coats",
          slug: "jackets-coats",
          title: "Men's Jackets & Coats",
          subtitle:
            "Discover our wide selection of stylish jackets and coats for men: from leather jackets to bombers, vests, peacoats and puffer jackets.",
        },
      },
      bags: {
        name: "Bags",
        title: "Men's Bags",
        subtitle:
          "Complete your look with a selection of luxury bags, including backpacks, belt bags and totes.",
      },
      shoes: {
        name: "Shoes",
        title: "Men's Shoes",
        subtitle:
          "Stride in style with finely crafted shoes for men - choose from a range of elegant styles from monk straps to oxfords, derbys, moccasins and driving shoes. Luxurious comfort - find the right sneakers from low top to high top or slip ons, or leather sandals and pool slides for a casual look.",
        sneakers: {
          name: "Sneakers",
          slug: "sneakers",
          title: "Men's Sneakers",
          subtitle:
            "Discover our newest collection of luxury sneakers for men in a wide range of styles: from the Chain Reaction and Trigreca , to other high top and low top sneakers embellished with signature motifs.",
        },
        "derby-shoes": {
          name: "Derby Shoes",
          slug: "derby-shoes",
          title: "Men's Derby Shoes",
          subtitle:
            "The Versace shoe collection for men includes lace-up Derby styles enriched with La Greca, Barocco and Medusa accents.",
        },
        "loafers-slippers": {
          name: "Loafers & Slippers",
          slug: "loafers-slippers",
          title: "Men's Loafers and Slippers",
          subtitle:
            "The Versace shoe collection for men includes slip-on loafers and slippers made from leather, suede, and velvet, enriched with La Greca motifs and Medusa hardware.",
        },
        boots: {
          name: "Boots",
          slug: "boots",
          title: "Men's Boots",
          subtitle:
            "Complete your look with Versace's luxury boots for men - Made in Italy from the finest materials.",
        },
        "sandals-slides": {
          name: "Sandals & Slides",
          slug: "sandals-slides",
          title: "Men's Sandals and Slides",
          subtitle:
            "Add a luxurious touch to your summer - explore Versace's selection of fashion slides and leather sandals in an array of styles and Medusa and Barocco embellishments. Pair your logo slides with Versace swimwear.",
        },
      },
      accessories: {
        name: "Accessories",
        title: "Men's Accessories",
        subtitle:
          "Travel in impeccable style with luxurious fashion accessories that bring your look to a new level of sophistication - from travel bags to formal shoes, add a touch of class to your look with fine leather belts and wallets Made in Italy. Finish off your look with necklaces and cufflinks for the gentleman of Versace.",
        belts: {
          name: "Belts",
          slug: "belts",
          title: "Men's Belts",
          subtitle:
            "Add a touch of luxury to your look - crafted in Italy from the finest materials, Versace's fine leather belts are embellished with iconic buckles inspired by the House's rich heritage.",
        },
        wallets: {
          name: "Wallets",
          slug: "wallets",
          title: "Men's Wallets",
          subtitle:
            "Keep your credit cards and essential documents at hand - browse our selection of card holders and wallets crafted from the finest materials in a wide range of colours and heritage prints.",
        },
      },
      "underwear-beachwear": {
        name: "Underwear and Beachwear",
        title: "Men's Underwear and Beachwear",
        "bathrobes-robes": {
          name: "Bathrobes",
          slug: "bathrobes-robes",
          title: "Men's Bathrobes",
          subtitle:
            "Bring iconic Versace prints and motifs to the beach, the pool or the bedroom. Browse the collection of luxury bathrobes for men, made from smooth silk and soft cotton.",
        },
      },
    },

    women: {
      title: "Women's Collection",
      subtitle:
        "For the ultimate Versace look, pair the latest runway styles with a luxurious handbag and expertly crafted shoes. Add statement accessories for a perfect finishing touch.",
      clothing: {
        name: "Clothing",
        title: "Women's Clothing",
        subtitle:
          "Find the perfect style for a modern look. Shop this season's most glamorous ready-to-wear from dresses, blouses, trousers and jackets. Elegant T-shirts, knitwear, beachwear and lingerie for a stylish wardrobe.",
        "blouses-tops": {
          name: "Blouses & Tops",
          title: "Women's Shirts and Tops",
          subtitle:
            "A true expression of Versace attitude—discover shirts, tops and bodysuits for women in the latest prints and styles, from silk shirts to lace bralette tops.",
        },
        "t-shirts-sweatshirts": {
          name: "T-Shirts & Sweatshirts",
          title: "Men's T-Shirts and Sweatshirts",
          subtitle:
            "Simply Versace—a selection of Versace women's t-shirts, sweatshirts and hoodies. Explore the possibilities of seasonal prints and brand codes like the GV Signature and La Medusa.",
        },
      },
    },

    unisex: {
      title: "Collection",
      subtitle: "",
      accessories: {
        title: "Accessories",
        subtitle: "",
        "soft-accessories": {
          name: "Soft Accessories",
          title: "Men's Soft Accessories",
          subtitle:
            "The Versace soft accessories selection includes hats, gloves, scarves and foulards made with the finest fabrics in statement Versace prints.",
        },
      },
    },
  },

  products: [
    {
      name: "La Greca Shirt",
      slug: "la-greca-shirt",
      images: {
        primary: "/images/1/image1.jpg",
        secondary: "/images/1/image2.jpg",
        modelFront: "/images/1/image3.jpg",
        modelBack: "/images/1/image4.jpg",
        materialCloseUp: "/images/1/image5.webp",
      },
      price: 1025,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Crafted in a lightweight cotton, this short-sleeved button-down shirt features the La Greca print and a relaxed camp collar.",
      details: [
        "La Greca print",
        "Short sleeves",
        "Camp collar",
        "Front button closure",
        "Side slits",
        "Outer Fabric: 52% Cotton, 48% Lyocell",
        "Outer Fabric 2: 52% Cotton, 48% Lyocell",
        "Machine wash cold (delicate)",
        "Do not bleach",
        "Do not tumble dry",
        "Cool iron on reverse with damp cloth on top",
        "Delicate dry clean",
        "Wash inside out",
      ],
      sku: "1003926-1A04992_5G320",
    },
    {
      name: "Barocco Silk Shirt",
      slug: "barocco-silk-shirt",
      images: {
        primary: "/images/2/image1.webp",
        secondary: "/images/2/image2.webp",
        modelFront: "/images/2/image3.webp",
        modelBack: "/images/2/image4.jpg",
        materialCloseUp: "/images/2/image5.webp",
      },
      price: 1550,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Crafted from pure silk this short-sleeved button-down shirt features the signature Barocco print - a beloved house code featuring stylised acanthus leaves.",
      details: [
        "Barocco print",
        "Button down front",
        "Collar",
        "Outer fabric: 100% Silk",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1003926-1A03044_5B000",
    },
    {
      name: "Barocco T-Shirt",
      slug: "barocco-t-shirt",
      images: {
        primary: "/images/3/image1.webp",
        secondary: "/images/3/image2.webp",
        modelFront: "/images/3/image3.jpg",
        modelBack: "/images/3/image4.webp",
      },
      price: 925,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "t-shirts-polos",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "In a slim silhouette, this short-sleeved cotton T-shirt features Versace's signature Barocco print - a beloved house code featuring stylised acanthus leaves.",
      details: [
        "Barocco print",
        "Short sleeves",
        "Ribbed crewneck",
        "Outer fabric: 100%  Cotton",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1006662-1A04612_5B000",
    },
    {
      name: "Barocco Shorts",
      slug: "barocco-shorts",
      images: {
        primary: "/images/4/image1.webp",
        secondary: "/images/4/image2.jpg",
        modelFront: "/images/4/image3.webp",
        modelBack: "/images/4/image4.webp",
        materialCloseUp: "/images/4/image5.jpg",
      },
      price: 1225,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "pants-shorts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "A comfortable design, these knee-length shorts are crafted from pure silk twill in the signature Barocco print.",
      details: [
        "Barocco print",
        "Lining: 100% Cupro",
        "Outer fabric: 100%  Silk",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1002476-1A03044_5B000",
    },
    {
      name: "Barocco Bucket Hat",
      slug: "barocco-bucket-hat",
      images: {
        primary: "/images/5/image1.webp",
        secondary: "/images/5/image2.webp",
        modelFront: "/images/5/image3.webp",
      },
      price: 625,
      brand: "Versace",
      category: "unisex",
      subcategory: "accessories",
      subSubcategory: "soft-accessories",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "A contemporary accessory, this bucket hat features the iconic Barocco print.",
      details: [
        "Barocco print",
        "Lining: 100% Polyamide",
        "Outer fabric: 100% Polyamide",
        "Do not bleach",
        "Do not dry clean",
        "Do not iron",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1001591-1A02963_5B000",
    },
    {
      name: "Metropolitano Check Wool Pants",
      slug: "metropolitano-check-wool-pants",
      tags: ["Runway Show"],
      images: {
        primary: "/images/6/image1.webp",
        secondary: "/images/6/image2.jpg",
        modelFront: "/images/6/image3.jpg",
        modelBack: "/images/6/image4.jpg",
        materialCloseUp: "/images/6/image5.jpg",
        video: "/images/6/video1.mp4",
      },
      price: 1950,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "pants-shorts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "A painterly Metropolitano Check motif outlines these tapered formal pants. A tailored style, they are finished with a front pleat and a concealed hook and zip closure.",
      details: [
        "Metropolitano Check print",
        "Belt loops",
        "Tapered fit",
        "Side pockets",
        "Concealed hook and zip closure",
        "Back welt pockets",
        "Outer Fabric: 100% Pure Virgin Wool",
        "Lining 1: 100% Cupro",
        "Lining 2: 100% Cotton",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
        "Cool iron",
        "Delicate dry clean",
      ],
      sku: "1006714-1A04925_5E050",
    },
    {
      name: "Medusa Hoodie",
      slug: "medusa-hoodie",
      images: {
        primary: "/images/7/image1.webp",
        secondary: "/images/7/image2.jpg",
        modelFront: "/images/7/image3.jpg",
        modelBack: "/images/7/image4.webp",
        materialCloseUp: "/images/7/image5.jpg",
      },
      price: 2150,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "sweatshirts",
      color: ["Brown", "Gray"],
      countInStock: 20,
      description:
        "Crafted from a soft cotton and cashmere blend, this hooded sweatshirt features a snap buttoned fastening, accented by Medusa hardware. In a sporty raglan cut, it's finished with a ribbed high-neck and trims.",
      details: [
        "Medusa hardware",
        "Long sleeves",
        "High-neck",
        "Hood",
        "Snap button closure",
        "Side welt pockets",
        "Elasticated hem and cuffs",
        "Ribbed trims",
        "Outer fabric: 91% Cotton 9% Cashmere",
        "Lining: 100% Cotton",
        "Trim: 100% Cotton",
        "Embroidery: 100% Viscose",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Do not wash",
      ],
      sku: "1006492-1A04502_1E210",
    },
    {
      name: "Barocco Silhouette Silk Shirt",
      slug: "barocco-silhouette-silk-shirt",
      images: {
        primary: "/images/8/image1.webp",
        secondary: "/images/8/image2.webp",
        modelFront: "/images/8/image3.webp",
        modelBack: "/images/8/image4.webp",
        materialCloseUp: "/images/8/image5.webp",
      },
      price: 1525,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Made from a fluid silk twill, this shirt has a loose fit, featuring a print rendition of a studded Barocco Silhouette pattern. The short-sleeved style is finished with a relaxed open collar and buttoned front.",
      details: [
        "Barocco Silhouette print",
        "Short sleeves",
        "Camp collar",
        "Front button closure",
        "Outer Composition: 100% Silk",
      ],
      sku: "1003926-1A06140_5B950",
    },
    {
      name: "Barocco 660 Silk Shirt",
      slug: "barocco-660-silk-shirt",
      images: {
        primary: "/images/9/image1.webp",
        secondary: "/images/9/image2.webp",
        modelFront: "/images/9/image3.webp",
        modelBack: "/images/9/image4.webp",
        materialCloseUp: "/images/9/image5.jpg",
        materialCloseUp: "/images/9/image6.webp",
        video: "/images/9/video1.mp4",
      },
      price: 1825,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Brown", "Gold"],
      countInStock: 20,
      description:
        "Crafted from pure silk, this long-sleeved shirt showcases the Barocco 660 print—a reimagining of an archival Barocco print.",
      details: [
        "Barocco 660 print",
        "Long sleeves",
        "Pointed collar",
        "Front button closure",
        "Buttoned cuffs",
        "Outer Composition: 100% Silk",
      ],
      sku: "1003941-1A05710_5B940",
    },
    {
      name: "Medusa La Greca Overshirt",
      slug: "medusa-la-greca-overshirt",
      images: {
        primary: "/images/10/image1.webp",
        secondary: "/images/10/image2.webp",
        modelFront: "/images/10/image3.webp",
        modelBack: "/images/10/image4.webp",
        materialCloseUp: "/images/10/image5.webp",
        video: "/images/10/video1.mp4",
      },
      price: 737,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "A lightweight design with wide short sleeves, this shirt features Medusa buttons and a tonal La Greca print inserts.",
      details: [
        "Medusa buttons",
        "La Greca print",
        "Short sleeves",
        "Camp collar",
        "Outer Fabric: 100% Polyamide",
        "Lining: 100% Cotton",
        "Trim: 100% Polyamide",
        "Cool iron",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Dry flat",
        "Machine wash cold (delicate)",
      ],
      sku: "1006019-1A04118_1B000",
    },
    {
      name: "Barocco Silhouette Silk Shorts",
      slug: "barocco-silhouette-silk-shorts",
      images: {
        primary: "/images/11/image1.webp",
        secondary: "/images/11/image2.jpg",
        modelFront: "/images/11/image3.jpg",
        modelBack: "/images/11/image4.jpg",
        materialCloseUp: "/images/11/image5.jpg",
      },
      price: 1250,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "pants-shorts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Crafted from silk twill, these knee-length shorts feature a printed stud rendition of the Barocco Silhouette motif. This wide-leg style is finished with an elasticized waistband.",
      details: [
        "Barocco Silhouette print",
        "Side pockets",
        "Elasticated waistband",
        "Outer composition: 100% Silk",
        "Lining: 100% Cupro",
      ],
      sku: "1002476-1A06140_5B950",
    },
    {
      name: "Versace Wide-Leg Jeans",
      slug: "versace-wide-leg-jeans",
      images: {
        primary: "/images/12/image1.webp",
        secondary: "/images/12/image2.webp",
        modelFront: "/images/12/image3.webp",
        modelBack: "/images/12/image4.webp",
        materialCloseUp: "/images/12/image5.webp",
      },
      price: 925,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "pants-shorts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "In a wide-leg silhouette, these washed jeans feature large denim panelling with contrast stitching and cargo pockets on the leg.",
      details: [
        "Denim panelling detail",
        "Belt loops",
        "Button and zip closure",
        "Cargo pockets",
        "Back and side pockets",
        "Outer composition: 100% Cotton",
        "Lining: 65% Polyester, 35% Cotton",
        "Trim: 100% Calf leather",
      ],
      sku: "1008624-1A05762_1D490",
    },
    {
      name: "Medusa Slim-Fit Jeans",
      slug: "medusa-slim-fit-jeans",
      images: {
        primary: "/images/13/image1.webp",
        secondary: "/images/13/image2.webp",
        modelFront: "/images/13/image3.webp",
        modelBack: "/images/13/image4.webp",
        materialCloseUp: "/images/13/image5.jpg",
      },
      price: 750,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "pants-shorts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "In a stretch cotton denim, these slim-fit jeans feature a five-pocket design with a three-dimensional Medusa plaque at the back.",
      details: [
        "Medusa plaque",
        "Belt loops",
        "Slim fit",
        "Five-pocket design",
        "Button and zip closure",
        "Outer fabric: 98% Cotton 2% Elastane",
        "Lining: 100% Cotton",
        "Trim: 100% Calf leather",
        "Cool iron on reverse with damp cloth on top",
        "Delicate dry clean",
        "Do not bleach",
        "Do not tumble dry",
        "Machine wash cold (delicate)",
        "Protect accessory before washing",
        "Wash inside out",
      ],
      sku: "A81832-1A03458_1D210",
    },
    {
      name: "Studded Short-Sleeved Polo Shirt",
      slug: "studded-short-sleeved-polo-shirt",
      images: {
        primary: "/images/14/image1.webp",
        secondary: "/images/14/image2.webp",
        modelFront: "/images/14/image3.webp",
        modelBack: "/images/14/image4.webp",
        materialCloseUp: "/images/14/image5.jpg",
      },
      price: 1125,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "t-shirts-polos",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Crafted in a lightweight, organic cotton piqué, this slim fitting polo shirt features a studded collar in the Barocco Silhouette pattern and embroidered logo lettering at the chest.",
      details: [
        "Studded Barocco Silhouette collar",
        "Embroidered logo detail",
        "Short sleeves",
        "Three-button placket",
        "Outer composition: 100% Cotton",
        "Embroidery: 100% Viscose",
        "Trim: 100% Cotton",
      ],
      sku: "1008502-1A06080_1B000",
    },
    {
      name: "Barocco Silhouette T-Shirt",
      slug: "barocco-silhouette-t-shirt",
      images: {
        primary: "/images/15/image1.webp",
        secondary: "/images/15/image2.webp",
        modelFront: "/images/15/image3.webp",
        modelBack: "/images/15/image4.webp",
      },
      price: 950,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "t-shirts-polos",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Crafted from cotton jersey, this short-sleeved T-shirt features a printed stud rendition of the Barocco Silhouette motif.",
      details: [
        "Barocco Silhouette print",
        "Short sleeves",
        "Crewneck",
        "Outer composition: 100% Cotton",
      ],
      sku: "1008969-1A06408_2B510",
    },
    {
      name: "Embroidered Varsity Logo T-Shirt",
      slug: "embroidered-varsity-logo-t-shirt",
      images: {
        primary: "/images/16/image1.jpg",
        secondary: "/images/16/image2.jpg",
        modelFront: "/images/16/image3.jpg",
        modelBack: "/images/16/image4.jpg",
        materialCloseUp: "/images/16/image5.jpg",
      },
      price: 675,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "t-shirts-polos",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Showcasing a Varsity whip-stitched logo, this short-sleeved T-shirt is a proud symbol of belonging to the Versace family. Made from cotton in a regular fit, this style is finished with a ribbed crewneck.",
      details: [
        "Embroidered Varsity logo",
        "Short sleeves",
        "Crewneck",
        "Outer composition: 100% Cotton",
        "Embroidery: 100% Polyester",
        "Trim: 100% Cotton",
      ],
      sku: "1008465-1A06055_1R780",
    },
    {
      name: "Medusa Logo T-Shirt",
      slug: "medusa-logo-t-shirt",
      images: {
        primary: "/images/17/image1.webp",
        materialCloseUp: "/images/17/image2.webp",
        secondary: "/images/17/image3.webp",
      },
      price: 1075,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "t-shirts-polos",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Made from cotton jersey, this short-sleeved T-Shirt has a regular fit, featuring an embroidered Medusa and logo at the front.",
      details: [
        "Medusa embroidery",
        "Logo",
        "Short sleeves",
        "Ribbed crewneck",
        "Outer Fabric: 100% Cotton",
        "Embroidery: 100% Viscose",
        "Trim: 100% Cotton",
        "Machine wash cold (delicate)",
        "Do not bleach",
        "Do not tumble dry",
        "Cool iron on reverse with damp cloth on top",
        "Delicate dry clean",
        "Wash inside out",
      ],
      sku: "1006984-1A04967_1W010",
    },
    {
      name: "Trigreca Sneakers",
      slug: "trigreca-sneakers",
      images: {
        primary: "/images/18/image1.webp",
        secondary: "/images/18/image2.webp",
        top: "/images/18/image3.webp",
        bottom: "/images/18/image4.webp",
        back: "/images/18/image5.webp",
        model: "/images/18/image6.webp",
      },
      price: 1025,
      brand: "Versace",
      category: "men",
      subcategory: "shoes",
      subSubcategory: "sneakers",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "The Trigreca trainers bring innovation to the brand's ever-evolving aesthetic. Three-dimensional Greca executions on the soles offer an impactful landing with the \"Greca Cushioning System.\" In a subtle nod to Versace's home city, the uppers have a discrete print of Milan's coordinates.",
      details: [
        "Low top",
        "Lace up",
        "Round toe",
        "Trigreca print on tongue and heel counter",
        "Printed coordinates of Milan",
        "Top-stitch detailing",
        "Rubber Greca soles",
        "Lining 1: 100% Calf leather",
        "Lining 2: 100% Calf leather",
        "Trim 1: 100% Nylon",
        "Trim 2: 100% Calf leather",
        "Trim 3: 90% Polyester, 10% Elastane",
        "Sole: 100% Rubber",
      ],
      sku: "DSU8094-1A04984_2EA00",
    },
    {
      name: "Greca Trainers",
      slug: "greca-trainers",
      images: {
        primary: "/images/19/image1.webp",
        top: "/images/19/image2.webp",
        bottom: "/images/19/image3.webp",
        secondary: "/images/19/image4.webp",
        model: "/images/19/image5.webp",
      },
      price: 695,
      brand: "Versace",
      category: "men",
      subcategory: "shoes",
      subSubcategory: "sneakers",
      color: ["Blue", "White"],
      countInStock: 20,
      description:
        "Characterized by an engraved Greca pattern on vulcanized rubber soles and side Greca web, the low-top silhouette features leather uppers and a lace-up design. A back logo stamp accents the lace-up style.",
      details: [
        "Greca webbing",
        "Low top",
        "Lace up",
        "Logo on heel counter",
        "Upper: 100% Calf leather",
        "Insole: 100% Calf leather",
        "Sole: 100% Rubber",
        "Trim: 100% Calf leather",
        "Made in Italy",
      ],
      sku: "DSU8404-1A00775_2W340",
    },
    {
      name: "Odissea Sneakers",
      slug: "odissea-sneakers",
      images: {
        primary: "/images/20/image1.webp",
        secondary: "/images/20/image2.webp",
        top: "/images/20/image3.webp",
        back: "/images/20/image4.webp",
        model: "/images/20/image5.webp",
      },
      price: 1050,
      brand: "Versace",
      category: "men",
      subcategory: "shoes",
      subSubcategory: "sneakers",
      color: ["Blue", "White"],
      countInStock: 20,
      description:
        "A futuristic and dynamic design, these lightweight slip-on sneakers are set on rubber soles with perforated toe caps. A rubberized La Medusa features on the uppers for a three-dimensional effect.",
      details: [
        "La Medusa",
        "Perforated toe caps",
        "Logo patch on tongue",
        "Upper: 100% Calf Leather",
        "Sole: 100% EVA",
        "Made in Italy",
      ],
      sku: "1004524-1A02259_1E010",
    },
    {
      name: "Versace Allover Silk Shirt",
      slug: "versace-allover-silk-shirt",
      images: {
        primary: "/images/21/image1.jpg",
        secondary: "/images/21/image2.webp",
        modelFront: "/images/21/image3.jpg",
        modelBack: "/images/21/image4.jpg",
        materialCloseUp: "/images/21/image5.webp",
      },
      price: 1525,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "Made from a fluid silk twill, this shirt has a regular fit, featuring a Versace Allover logo print. The short-sleeved style is finished with a relaxed open collar and buttoned front.",
      details: [
        "Versace Allover print",
        "Short sleeves",
        "Notched collar",
        "Front button closure",
        "Outer composition: 100% Silk",
        "Do not wash",
        "Do not bleach",
        "Do not tumble dry",
        "Cool iron",
        "Delicate dry clean",
      ],
      sku: "1003926-1A06877_5P440",
    },
    {
      name: "Silver Baroque Silk Shirt",
      slug: "silver-baroque-silk-shirt",
      images: {
        primary: "/images/22/image1.webp",
        secondary: "/images/22/image2.webp",
        modelFront: "/images/22/image3.webp",
        modelBack: "/images/22/image4.webp",
        materialCloseUp: "/images/22/image5.webp",
      },
      price: 1275,
      brand: "Versace",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Silver"],
      countInStock: 20,
      description:
        "Made from pure silk, this short-sleeved shirt features a tonal Silver Baroque print with a loose fit. The button-down style is finished with a pointed collar and wide sleeves.",
      details: [
        "Silver Baroque motif",
        "Logo",
        "Pointed collar",
        "Short sleeves",
        "Front button closure",
        "Outer fabric: 100% Silk",
        "Do not wash",
        "Do not bleach",
        "Do not tumble dry",
        "Cool iron",
        "Delicate dry clean",
      ],
      sku: "1006378-1A04840_5E110",
    },
    {
      name: "Horsebit Print Cotton Polo Shirt",
      slug: "horsebit-print-cotton-polo-shirt",
      images: {
        primary: "/images/23/image1.avif",
        secondary: "/images/23/image2.avif",
        modelFront: "/images/23/image4.avif",
        modelBack: "/images/23/image5.avif",
        materialCloseUp: "/images/23/image3.avif",
        modelShowcaseFront: "/images/23/image6.avif",
      },
      price: 1150,
      brand: "Gucci",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "t-shirts-polos",
      color: ["Fuchsia", "Turquoise"],
      countInStock: 20,
      description:
        "During the Cruise 2023 Gucci Cosmogonie fashion show, new constellations of House codes were presented. The now recognizable Horsebit continues to decorate new iterations of the polo shirt.",
      details: [
        "Ivory and red Horsebit print stretch cotton piquet",
        "Multicolor trim",
        "Short sleeve",
        "Made in Italy",
        "Fabric: 94% Cotton, 6% Elastane.",
        "Trimming: 100% Cotton.",
      ],
      sku: "717391_XJEWA_9376",
    },
    {
      name: "Striped Cotton Boxy Shirt",
      slug: "striped-cotton-boxy-shirt",
      images: {
        primary: "/images/24/image1.avif",
        secondary: "/images/24/image2.avif",
        modelFront: "/images/24/image4.avif",
        modelBack: "/images/24/image5.avif",
        modelShowcaseFront: "/images/24/image6.avif",
        modelShowcaseBack: "/images/24/image7.avif",
        materialCloseUp: "/images/24/image3.avif",
      },
      price: 780,
      brand: "Gucci",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "shirts",
      color: ["Blue"],
      countInStock: 20,
      description:
        "In a more relaxed fit this striped Oxford cotton shirt speaks to the Gucci concept of tailoring that permeates each collection.",
      details: [
        "Blue and white striped cotton",
        "Long sleeves",
        "Point collar",
        "Button-through cuffs",
        "Front button closure",
        "Boxy fit",
        "Made in Italy",
        "The product shown in this image is a size 15++",
        "Fabric: 100% Cotton.",
      ],
      sku: "1006378-1A04840_5E110",
    },
    {
      name: "Gucci HA HA HA Herringbone Jacket",
      slug: "gucci-ha-ha-ha-herringbone-jacket",
      images: {
        primary: "/images/25/image1.avif",
        secondary: "/images/25/image2.avif",
        materialCloseUp: "/images/25/image3.avif",
        tertiary: "/images/25/image6.avif",
        modelFront: "/images/25/image4.avif",
        modelBack: "/images/25/image5.avif",
        modelShowcaseFront: "/images/25/image7.avif",
        modelShowcaseBack: "/images/25/image8.avif",
      },
      price: 3980,
      brand: "Gucci",
      category: "men",
      subcategory: "clothing",
      subSubcategory: "jackets-coats",
      color: ["Brown"],
      countInStock: 20,
      description:
        "Gucci HA HA HA expresses the friendship between Gucci's Creative Director, Alessandro Michele, and the British singer-songwriter and actor, Harry Styles. Featuring whimsical motifs and vibrant colors, the special collection of ready-to-wear, shoes and accessories represents the landing place of an inventive two-person journey. This double-breasted jacket is crafted from dark camel solid herringbone wool.",
      details: [
        "Dark camel solid herringbone wool",
        "Created by Alessandro Michele and Harry Styles",
        "Fully lined",
        "Double-breasted",
        "Peak lapel",
        "Full canvas construction",
        "Front pockets",
        "Buttoned cuffs",
        "Button closure",
        'Length: 30.3", based on a size 46 (IT)',
        "Made in Italy",
        "The product shown in this image is a size 46 (IT)",
        "Fabric: 100% Wool.",
        "Lining: 100% Viscose.",
        "Sleeve lining: 100% Cupro.",
        "Application: 80% Polyester, 20% Metallised fiber.",
      ],
      sku: "671980_ZAG95_2240",
    },
    {
      name: "GG Geometric Lace Shirt",
      slug: "gg-geometric-lace-shirt",
      images: {
        primary: "/images/26/image1.avif",
        secondary: "/images/26/image2.avif",
        modelFront: "/images/26/image4.avif",
        modelBack: "/images/26/image5.avif",
        modelShowcaseFront: "/images/26/image6.avif",
        modelShowcaseBack: "/images/26/image7.avif",
        materialCloseUp: "/images/26/image3.avif",
      },
      price: 2400,
      brand: "Gucci",
      category: "women",
      subcategory: "clothing",
      subSubcategory: "blouses-tops",
      color: ["Black"],
      countInStock: 20,
      description:
        "With an eye to the theme of seasonality first seen in past collections, a proposal of daywear and formal wear is presented in new fabrics, patterns and fits, mix and matched with sensual and hyper-feminine silhouettes that take on a '70s influence. This shirt is presented in transluscent black lace with an intricate GG geometric motif.",
      details: [
        "Black GG geometric lace",
        "Detachable camisole",
        "High neck",
        "Puff sleeves",
        "Button closure",
        'Length: 27.5", based on a size 40 (IT)',
        "Made in Italy",
        "The product shown in this image is a size 40 (IT)",
        "Top: Fabric: 84% Polyamide, 16% Cotton.",
        "Trimming: 70% Cotton, 30% Polyamide.",
        "Petticoat: Inner: 75% Acetate, 25% Silk.",
        "Trimming: 90% Cotton, 10% Polyamide.",
      ],
      sku: "717104_ZAKBX_1000",
    },
  ],

  countries: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua &amp; Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia &amp; Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Cape Verde",
    "Cayman Islands",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote D Ivoire",
    "Croatia",
    "Cruise Ship",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Polynesia",
    "French West Indies",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kuwait",
    "Kyrgyz Republic",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Pierre &amp; Miquelon",
    "Samoa",
    "San Marino",
    "Satellite",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "St Kitts &amp; Nevis",
    "St Lucia",
    "St Vincent",
    "St. Lucia",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor L'Este",
    "Togo",
    "Tonga",
    "Trinidad &amp; Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks &amp; Caicos",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Virgin Islands (US)",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
};

export default data;
